# -*- coding: utf-8 -*-
"""
GitDeployService
~~~~~~~~~~~~~~~~
Pushes a generated Odoo module folder to a new (or existing) GitHub repository.
"""

import os
import base64
import logging
import mimetypes
from pathlib import Path
from typing import Optional

import httpx
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)

# ── GitHub REST helpers ──────────────────────────────────────────────────────

GITHUB_API = "https://api.github.com"


def _headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _is_binary(path: Path) -> bool:
    """Return True if the file should be treated as binary (non-text)."""
    mime, _ = mimetypes.guess_type(str(path))
    if mime and not mime.startswith("text"):
        return True
    # Fallback: try reading a small chunk
    try:
        path.read_text(encoding="utf-8")
        return False
    except (UnicodeDecodeError, PermissionError):
        return True


# ── Main service class ───────────────────────────────────────────────────────

class GitDeployService:
    """
    Deploys a local module directory to GitHub using the GitHub Contents API
    (no git binary required — pure HTTP).
    """

    def __init__(self):
        self.token: str = os.getenv("GITHUB_TOKEN", "").strip()
        self.user: str = os.getenv("GITHUB_USER", "").strip()
        self.org: Optional[str] = os.getenv("GITHUB_ORG", "").strip() or None
        self.private: bool = os.getenv("GITHUB_PRIVATE", "false").lower() == "true"

        if not self.token:
            raise EnvironmentError(
                "GITHUB_TOKEN is missing. Add it to your .env file.\n"
                "Create one at https://github.com/settings/tokens (needs 'repo' scope)."
            )
        if not self.user:
            raise EnvironmentError(
                "GITHUB_USER is missing. Add your GitHub username to .env."
            )

        self._owner = self.org or self.user

    # ── Public API ───────────────────────────────────────────────────────────

    def deploy(self, module_path: str, repo_name: Optional[str] = None) -> str:
        """
        Create a GitHub repo (if it doesn't exist) and push every file in
        *module_path* to it.

        Args:
            module_path : Absolute path to the generated Odoo module directory.
            repo_name   : Repository name to use. Defaults to the folder name.

        Returns:
            The HTML URL of the created/updated repository.
        """
        module_dir = Path(module_path)
        if not module_dir.is_dir():
            raise ValueError(f"Module path does not exist: {module_path}")

        repo_name = repo_name or module_dir.name
        # GitHub repo names can't have spaces
        repo_name = repo_name.replace(" ", "_").lower()

        logger.info("Starting GitHub deployment → %s/%s", self._owner, repo_name)

        repo_url, default_branch = self._ensure_repo(repo_name)
        self._push_directory(module_dir, repo_name, default_branch)

        logger.info("✅ Deployment complete: %s", repo_url)
        return repo_url

    # ── Private helpers ──────────────────────────────────────────────────────

    def _ensure_repo(self, repo_name: str) -> tuple[str, str]:
        """
        Create the repo if it doesn't exist. Returns (html_url, default_branch).
        """
        # Check if repo already exists
        check_url = f"{GITHUB_API}/repos/{self._owner}/{repo_name}"
        with httpx.Client(timeout=30) as client:
            r = client.get(check_url, headers=_headers(self.token))

        if r.status_code == 200:
            data = r.json()
            logger.info("Repo already exists: %s", data["html_url"])
            return data["html_url"], data.get("default_branch", "main")

        # Create new repo
        if self.org:
            create_url = f"{GITHUB_API}/orgs/{self.org}/repos"
        else:
            create_url = f"{GITHUB_API}/user/repos"

        payload = {
            "name": repo_name,
            "description": f"Odoo module generated by Odoo AI Module Generator",
            "private": self.private,
            "auto_init": True,          # creates an initial commit with README
            "default_branch": "main",
        }

        with httpx.Client(timeout=30) as client:
            r = client.post(create_url, json=payload, headers=_headers(self.token))

        if r.status_code not in (200, 201):
            raise RuntimeError(
                f"Failed to create GitHub repo '{repo_name}': "
                f"HTTP {r.status_code} — {r.text}"
            )

        data = r.json()
        logger.info("Created repo: %s", data["html_url"])
        return data["html_url"], data.get("default_branch", "main")

    def _get_file_sha(self, repo_name: str, file_path: str) -> Optional[str]:
        """Get the SHA of an existing file (needed for update commits)."""
        url = f"{GITHUB_API}/repos/{self._owner}/{repo_name}/contents/{file_path}"
        with httpx.Client(timeout=15) as client:
            r = client.get(url, headers=_headers(self.token))
        if r.status_code == 200:
            return r.json().get("sha")
        return None

    def _push_file(self, repo_name: str, file_path_in_repo: str,
                   content_bytes: bytes, branch: str) -> None:
        """Create or update a single file via the GitHub Contents API."""
        url = (
            f"{GITHUB_API}/repos/{self._owner}/{repo_name}"
            f"/contents/{file_path_in_repo}"
        )
        encoded = base64.b64encode(content_bytes).decode("utf-8")
        sha = self._get_file_sha(repo_name, file_path_in_repo)

        payload: dict = {
            "message": f"Add {file_path_in_repo}",
            "content": encoded,
            "branch": branch,
        }
        if sha:
            payload["sha"] = sha          # required for update
            payload["message"] = f"Update {file_path_in_repo}"

        with httpx.Client(timeout=30) as client:
            r = client.put(url, json=payload, headers=_headers(self.token))

        if r.status_code not in (200, 201):
            raise RuntimeError(
                f"Failed to push '{file_path_in_repo}': "
                f"HTTP {r.status_code} — {r.text[:300]}"
            )

    def _push_directory(self, directory: Path, repo_name: str, branch: str) -> None:
        """Walk the module directory and push every file to GitHub."""
        files = [p for p in directory.rglob("*") if p.is_file()]
        logger.info("Pushing %d files to GitHub...", len(files))

        for file_path in files:
            # Skip Python cache files — no point committing those
            if "__pycache__" in file_path.parts or file_path.suffix == ".pyc":
                continue

            rel = file_path.relative_to(directory)
            repo_file_path = str(rel).replace("\\", "/")   # forward slashes for GitHub

            try:
                content_bytes = file_path.read_bytes()
                self._push_file(repo_name, repo_file_path, content_bytes, branch)
                logger.debug("Pushed: %s", repo_file_path)
            except Exception as exc:
                logger.warning("Skipped %s: %s", repo_file_path, exc)

        logger.info("All files pushed.")